### ISSUE TITLE
Auto-update hosts file.

### ISSUE THREAD

**Issue by ZycatForce** [TrackerControl/tracker-control-android#252]
I'm requesting an auto-update hosts file feature. We should be able to set the time interval and whether to update on mobile or Wi-Fi only.

Thanks.

**Comment by kasnder** [comment]
This is a great suggestion.

However, TrackerControl uses classical host lists only as a backup, and a combination of Oxford X-Ray and Disconnect.me / Firefox by default.

From experience, tracking domains don't change a lot, so not sure this is super urgent.

**Comment by Ilithy** [comment]
Hello, I am rather for this feature, some hosts files are more extensive than those used, for example: [https://github.com/StevenBlack/hosts](StevenBlack Hosts)

And since it is updated regularly, the functionality goes hand in hand for users who appreciate the protection of naviaction by hosts file. (Thanks for your work, your application is really very very useful)

**Comment by karolyi** [comment]
Not sure this adds any meaningful information/incentive, but the lists you mentioned don't block everything. The https://github.com/StevenBlack/hosts/ hostlist (defined in the "Hosts file URL") includes stuff that is more easy to add to, just like I'm underway on adding to that list a host that is a tracker from salesforce.

I'm fine with updating the list manually from time to time, but an automated update on the defined host list(s) would be more streamlined.

**Comment by mbnoimi** [comment]
> From experience, tracking domains don't change a lot, so not sure this is super urgent.

Practically this is urgent. I frequently sees ads unless I update it manually which is a lame process

**Comment by vdbhb59** [comment]
Rephrased. This should be a feature to go with. It is 4th year since it was requested.
