### ISSUE TITLE
TrackerControl data usage info

### ISSUE THREAD

**Issue by lucamp** [TrackerControl/tracker-control-android#288]
If I go to Android's TrackeControl app info, then data usage, the OS report nearly 700 MB of data downloaded in 2 weeks.
As far as I understand TC use an internal blacklist that must be downloaded, plus my personal blacklist that I update manually evey 2 weeks (energized block basic ~10 MB).
TrackerControl is always on and other apps use its VPN, nevertheless their internet data usage are stated in every app.

This amount of data seems little bit too much to me, is Android having issues recognising TC data usage or is TC really using this amount of bandwidth?

Fdroid 2021.12.09

Thanks

![Screenshot_2022-02-02-15-28-56-66](https://user-images.githubusercontent.com/15078341/152176611-d4d58b4b-65a4-452c-b154-3942c711f773.jpg)

**Comment by kasnder** [comment]
Since traffic of other apps goes through TC, other apps' traffic gets attributed to TC.

This is a part of Android, and I can't do anything about it.

**Comment by Snehargho123** [comment]
Hi, I understand that trackercontrol will have internet usage associated with it in android settings. But, shouldn't this data usage amount to the total data usage in a given period of time? If android settings is reporting this data usage since all traffic of the device goes through trackercontrol then android should report a higher amount of data in my case. Android reports that my total data usage in a day is 1.7 gb but trackercontrol used around 30 mb. How does that work?
