### ISSUE TITLE
Allow blocking of any domain or IP

### ISSUE THREAD

**Issue by prajwal-koirala-0000** [TrackerControl/tracker-control-android#310]
Currently u can only block a domain or an IP if it's in the Steven black hosts file but we want an option where if there is a tracker and it's not on the official list, the users should be able to block them too.

**Comment by kasnder** [comment]
Thank you for the suggestion. To keep things simple in the app, I currently have no plans to implement this. I'm sorry!

**Comment by prajwal-koirala-0000** [comment]
> Thank you for the suggestion. To keep things simple in the app, I currently have no plans to implement this. I'm sorry!

I don't write java but this would be easy to implement, also if I donate $100 can this be added?

**Comment by kasnder** [comment]
> > Thank you for the suggestion. To keep things simple in the app, I currently have no plans to implement this. I'm sorry!
> 
> I don't write java but this would be easy to implement, also if I donate $100 can this be added?

Other apps, like NetGuard, seem to offer this funtionality already. That's why I don't think this needs to be added to TC, too.

**Comment by prajwal-koirala-0000** [comment]
> 

I came from netguard, it sucks dick u only use that when u have no other choice.

This is way better than that, don't put this app on the same range as that one.

**Comment by prajwal-koirala-0000** [comment]
@kasnder 

Since netguard stopped development this is more necessary than ever.

**Comment by ilonachan** [comment]
@kasnder Even if NetGuard was still/ever a viable alternative, the argument that therefore you shouldn't also have this (in my opinion, basic) feature is just weird. Wouldn't you want your app to be as usable as possible? Rather than, idk, requiring the user to chain TC and NG together _somehow_ (I don't even know how that would work) just so they can mix and match this ONE feature?

Which, I repeat, seems like very basic user control: just have a list of custom blocked domains at the bottom of the predefined ones, where the user can add custom-typed lines. Would that really be so difficult? I'm not even asking for deep integration, like idk, in the traffic log have a menu option to pick the url from any observed outbound request to add it as a custom block (tho that would be a great convenience feature & doesn't seem too difficult either, but I get that it could be)
